#!/bin/bash -e
SDIR=$(cd "$(dirname "$0")" ; pwd -P)
T=$SDIR/step
source $SDIR/other

DESKTOP=windows-x64

$SDIR/gen-kd

STEP=0
# SDK
source $T/copyDesktopSDK
source $T/buildDesktopSDK
source $T/genWindowsLib hw
# App
source $T/copyDesktopSrc
source $T/buildDesktop
