#!/bin/bash -e
SDIR=$(cd "$(dirname "$0")" ; pwd -P)
T=$SDIR/step
source $SDIR/other

DESKTOP=windows-x64

$SDIR/gen-kd

STEP=0
source $T/copyDesktopSDK
source $T/copyWindowsSrc
source $T/buildDesktopSDK
source $T/genWindowsLib hw
source $T/renameDesktopIncludes
source $T/buildDesktop
