#!/bin/bash

STEP=$((STEP+1))
echo -e "\n> > > > Step №$STEP. Build SDK for iOS"

BUILD_DIR=$SDIR/../sdk-ios/hw/build/XCFrameworks/release

cd $SDIR/../sdk-ios
./gradlew assembleHwReleaseXCFramework
cd $BUILD_DIR
zip -r hw.xcframework.zip hw.xcframework
ln -sf $BUILD_DIR/hw.xcframework.zip $SDIR/../ver-ios/app/local/hw/hw.xcframework.zip
