#!/bin/bash

STEP=$((STEP+1))
echo -e "\n> > > > Step №$STEP. Copy SDK files to Desktop: $DESKTOP"

FILE=$SDIR/../copy-sdk.txt
SRC=$SDIR/../ver-android/app/src/main/kotlin/org/opengamestudio
DST=$SDIR/../sdk-$DESKTOP/hw/src/nativeMain/kotlin/org/opengamestudio

# https://stackoverflow.com/a/1521470/3404710
cat $FILE | while read ln || [[ -n $ln ]]; do
    echo $ln
    cp $SRC/$ln $DST/ignore.$ln
done
