#!/bin/bash

STEP=$((STEP+1))
echo -e "\n> > > > Step №$STEP. Copy source files for $DESKTOP"

FILES=$SDIR/../copy-windows.txt
SRC=$SDIR/../ver-mac-x64/src
DST=$SDIR/../ver-$DESKTOP/src

# https://stackoverflow.com/a/1521470/3404710
cat $FILES | while read file || [[ -n $file ]]; do
    echo $file
    cp $SRC/$file $DST/$file
done
