#!/bin/bash

STEP=$((STEP+1))
echo -e "\n> > > > Step №$STEP. Copy source files to Desktop: $DESKTOP"

FILE=$SDIR/../copy-windows.txt
SRC=$SDIR/../ver-mac-x64/src
DST=$SDIR/../ver-$DESKTOP/src

# https://stackoverflow.com/a/1521470/3404710
cat $FILE | while read ln || [[ -n $ln ]]; do
    echo $ln
    cp $SRC/$ln $DST/ignore.$ln
done
